# Site settings
title: Edgar Cirilo
description: My personal site
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Edgar Cirilo
user_description: I'm a Software Engineer, Microservices developer. Highly scalable, and cloud-native applications.
user_title: Software Engineer
email: edgarciriloglez@gmail.com
twitter_username: ecirilog
github_username:  eddy16

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
